config/routes.rb
Rails.application.routes.draw do
  get 'contact/contact'

  resources :advertisings
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/advertising.rb
class Advertising
  include Mongoid::Document
  include Mongoid::Paperclip
  field :name, type: String
  field :email, type: String
  field :description, type: String
  field :amount, type: Integer
  field :payment, type: String
  field :redirect_link, type: String
  #field :image, type: Attachment
  has_mongoid_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/advertisings_controller.rb
class AdvertisingsController < ApplicationController
  before_action :set_advertising, only: [:show, :edit, :update, :destroy]

  # GET /advertisings
  # GET /advertisings.json
  def index
    @advertisings = Advertising.all
  end

  # GET /advertisings/1
  # GET /advertisings/1.json
  def show
  end

  # GET /advertisings/new
  def new
    @advertising = Advertising.new
  end

  # GET /advertisings/1/edit
  def edit
  end

  # POST /advertisings
  # POST /advertisings.json
  def create
    @advertising = Advertising.new(advertising_params)

    respond_to do |format|
      if @advertising.save
        format.html { redirect_to @advertising, notice: 'Advertising was successfully created.' }
        format.json { render :show, status: :created, location: @advertising }
      else
        format.html { render :new }
        format.json { render json: @advertising.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisings/1
  # PATCH/PUT /advertisings/1.json
  def update
    respond_to do |format|
      if @advertising.update(advertising_params)
        format.html { redirect_to @advertising, notice: 'Advertising was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertising }
      else
        format.html { render :edit }
        format.json { render json: @advertising.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisings/1
  # DELETE /advertisings/1.json
  def destroy
    @advertising.destroy
    respond_to do |format|
      format.html { redirect_to advertisings_url, notice: 'Advertising was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertising
      @advertising = Advertising.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertising_params
      params.require(:advertising).permit(:name, :email, :description, :amount, :payment, :redirect_link, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @advertisings = Advertising.all
  end
end

app/helpers/advertisings_helper.rb
module AdvertisingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/advertisings/_form.html.erb
<%= form_with(model: advertising, html: { multipart: true }, local: true) do |form| %>
  <% if advertising.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertising.errors.count, "error") %> prohibited this advertising from being saved:</h2>

      <ul>
      <% advertising.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :advertising_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :advertising_email %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :advertising_description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :advertising_amount %>
  </div>

  <div class="field">
    <%= form.label :payment %>
    <%= form.text_field :payment, id: :advertising_payment %>
  </div>

  <div class="field">
    <%= form.label :redirect_link %>
    <%= form.text_field :redirect_link, id: :advertising_redirect_link %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :advertising_image %>

  </div>

  <div class="field">
    <span><%= advertising.image %></span>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advertisings/edit.html.erb
<h1>Editing Advertising</h1>

<%= render 'form', advertising: @advertising %>

<%= link_to 'Show', @advertising %> |
<%= link_to 'Back', advertisings_path %>

app/views/advertisings/index.html.erb
<div class="main">
  <div class="wrapper">
    <div class="option" id="example-vertical">
      <div id="steps">
      <button type="button" class="btn btn-outline-primary">Primeiro</button>
      </div>
      <div id="steps">
      <button type="button" class="btn btn-outline-primary">segundo</button>
      </div>
    </div>

    <div class="content">
      <div class="upload-btn-wrapper">
        <button class="btn text-center">Upload File</button>
        <input type="file" name="myfile">
      </div>
    </div>
  </div>
</div>






<p id="notice"><%= notice %></p>

<h1>Advertisings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Payment</th>
      <th>Redirect link</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisings.each do |advertising| %>
      <tr>
        <td><%= advertising.name %></td>
        <td><%= advertising.email %></td>
        <td><%= advertising.description %></td>
        <td><%= advertising.amount %></td>
        <td><%= advertising.payment %></td>
        <td><%= advertising.redirect_link %></td>
        <td><%= advertising.image %></td>
        <td><%= link_to 'Show', advertising %></td>
        <td><%= link_to 'Edit', edit_advertising_path(advertising) %></td>
        <td><%= link_to 'Destroy', advertising, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertising', new_advertising_path %>

app/views/advertisings/new.html.erb
<h1>New Advertising</h1>

<%= render 'form', advertising: @advertising %>

<%= link_to 'Back', advertisings_path %>

app/views/advertisings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @advertising.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @advertising.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @advertising.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @advertising.amount %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @advertising.payment %>
</p>

<p>
  <strong>Redirect link:</strong>
  <%= @advertising.redirect_link %>
</p>

<p>
  <strong>Image:</strong>
  <%= @advertising.image %>
</p>

<%= link_to 'Edit', edit_advertising_path(@advertising) %> |
<%= link_to 'Back', advertisings_path %>

app/views/contact/contact.html.erb
<div class="main">
  <div class="wrapper">

    <div id="form">
      <form>

        <p class="h5 text-center mb-4">Write to us</p>

        <div class="md-form">
          <i class="fa fa-user-circle prefix grey-text"></i>
          <input type="text" id="form3" class="form-control">
          <label for="form3" >Your name</label>
        </div>

        <div class="md-form">
          <i class="fa fa-envelope prefix grey-text"></i>
          <input type="text" id="form2" class="form-control">
          <label for="form2">Your email</label>
        </div>

        <div class="md-form">
          <i class="fa fa-tag prefix grey-text"></i>
          <input type="text" id="form32" class="form-control">
          <label for="form34">Subject</label>
        </div>

        <div class="md-form">
          <i class="fa fa-pencil prefix grey-text"></i>
          <textarea type="text" id="form8" class="md-textarea" style="height: 100px"></textarea>
          <label for="form8">Your message</label>
        </div>

        <div class="text-center">
          <button class="btn btn-unique">Send <i class="fa fa-paper-plane-o ml-1"></i></button>
        </div>

      </form>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="main">
  <div class="wrapper">
    <div class="advertising float-left">
      <div id="carouselExampleControls" class="carousel slide">
        <div class="carousel-inner">
          <% @advertisings.each_with_index do |advertising, index| %>
            <div class="carousel-item <%='active' unless index!=0 %> ">
              <%= image_tag advertising.image, alt: advertising.name, class: "d-block w-100" %>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <div id="icons" class="text-center">
        <a href="https://www.facebook.com/junior.farias.792" target="_blank">
          <i class="fa fa-facebook-square" aria-hidden="true"></i>
        </a>
        <a href="https://www.facebook.com/junior.farias.792" target="_blank">
          <i class="fa fa-twitter-square" aria-hidden="true"></i>
        </a>
        <a href="https://www.facebook.com/junior.farias.792" target="_blank">
          <i class="fa fa-instagram" aria-hidden="true"></i>
        </a>
      </div>
    </div>
    <div id="ipay" class="float-left">
      <div id="poster" class="text-center">
        <p class="font-weight-bold">LAST PAID</p>
      </div>
      <div id="amount" class="text-center border border-dark rounded">
        <span class="ng-binding ng-scope">$1.000</span>
      </div>
      <div id="bet">
        <a class="btn btn-primary" href="http://0.0.0.0:3000/pay" role="button">cover supply</a>
      </div>
    </div>
  </div>
</div>


<!--<div class="main">-->
  <!--<div class="wrapper">-->
    <!--<div class="advertising float-left">-->
      <!--<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">-->
        <!--<div class="carousel-inner">-->
          <!--<div class="carousel-item active">-->
            <!--<img class="d-block w-100" src="https://a.slack-edge.com/436da/marketing/img/slack_logo.png" alt="First slide">-->
          <!--</div>-->
          <!--<div class="carousel-item">-->
            <!--<img class="d-block w-100" src="http://www.easycoop.com.br/web/emanager/noticias/imagens/pequena-casa-com-jardim_417887.jpg" alt="Second slide">-->
          <!--</div>-->
          <!--<div class="carousel-item">-->
            <!--<img class="d-block w-100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Casa_Guilherme_de_Almeida.jpg/1200px-Casa_Guilherme_de_Almeida.jpg" alt="Third slide">-->
          <!--</div>-->
        <!--</div>-->
        <!--<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">-->
          <!--<span class="carousel-control-prev-icon" aria-hidden="true"></span>-->
          <!--<span class="sr-only">Previous</span>-->
        <!--</a>-->
        <!--<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">-->
          <!--<span class="carousel-control-next-icon" aria-hidden="true"></span>-->
          <!--<span class="sr-only">Next</span>-->
        <!--</a>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="ipay float-sm-left text-center border border-dark rounded">-->
      <!--<span class="ng-binding ng-scope">$1.000</span>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gohigh</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    


  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
        <img src="/assets/crown.png" width="32" height="32" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact/contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="p">Press</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="ngo">NGO</a>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>

  </body>
</html>